# Generated by Django 5.1.1 on 2025-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, default='Не указан', max_length=20),
        ),
    ]
