# Generated by Django 5.1.1 on 2025-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_usermodel_birthday_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='title',
            field=models.CharField(blank=True, default='Без описания', max_length=128),
        ),
    ]
